version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - .:/app

    environment:
      - SECRET_KEY=devsccccccccc
      - DEBUG=1

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=Imeanforreal
