# Generated by Django 2.2.24 on 2021-07-31 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
            ],
        ),
    ]
