# Generated by Django 2.2.24 on 2021-08-01 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile_test', '0002_auto_20210731_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='users/profile_pic/65usnbY', verbose_name='Profile Picture'),
        ),
    ]
