# Generated by Django 4.2.1 on 2023-06-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile_test', '0003_myuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='users/profile_pic/ALHTLKG', verbose_name='Profile Picture'),
        ),
    ]
